# Chapter-7 (Quiz)

In [14]:
import pandas as pd

In [15]:
#Q. 01
d = {'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6], 'col4': [7, 8]} 
df = pd.DataFrame(d)
df

   col1  col2  col3  col4
0     1     3     5     7
1     2     4     6     8

In [16]:
#Q. 02
new_df = df[['col4']]
new_df

   col4
0     7
1     8

In [17]:
#Q. 03
df.index = ['first', 'second']
df

        col1  col2  col3  col4
first      1     3     5     7
second     2     4     6     8

In [18]:
#Q. 04
df.isna()

         col1   col2   col3   col4
first   False  False  False  False
second  False  False  False  False

In [22]:
#Q. 05
# print(df.describe())

#For mode as asked in question we need to write another line of code as we cannot get mode from df.describe()
mode = df.mode()
mode

   col1  col2  col3  col4
0     1     3     5     7
1     2     4     6     8